# Generated by Django 5.1.6 on 2025-03-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_baseuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
