# Generated by Django 5.1.6 on 2025-03-27 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
        ('user_management', '0003_alter_vendor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_management.vendor'),
        ),
    ]
