# Generated by Django 5.1.6 on 2025-03-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_product_vender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vender',
            new_name='vendor',
        ),
    ]
