# Generated by Django 5.1.6 on 2025-03-31 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_order_orderitem'),
        ('user_management', '0003_alter_vendor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='user_management.vendor'),
        ),
    ]
